site_name: Dartmouth Brain Imaging Center Handbook vX.X.X-dev
theme:
    name: material
    custom_dir: theme_customizations/
    favicon: images/favicon.png
    logo: images/logo.png
extra_javascript:
    - js/jquery-3.4.1.min.js
markdown_extensions:
    - toc:
        anchorlink: true
plugins:
    - search
docs_dir: 'src'
use_directory_urls: false
nav:
    - The DBIC Handbook:
      - Introduction: 01-introduction.md
