site_name: Dartmouth Brain Imaging Center Handbook vX.X.X-dev
theme:
    name: material
    custom_dir: theme_customizations/
    favicon: images/favicon.png
    logo: images/logo.png
extra_javascript:
    - js/jquery-3.4.1.min.js
markdown_extensions:
    - toc:
        anchorlink: true
plugins:
    - search
docs_dir: 'src'
use_directory_urls: false
nav:
    - Introduction: 01-introduction.md
    - A new study:
        - Human subjects: XXX.md
        - JEDCap: XXX.md
        - Experimental design: XXX.md
        - Pre-registration: XXX.md
    - Data Collection:
        - Stimuli delivery: XXX.md
        - Behavioral: XXX.md
        - MRI:
          - ReproIn naming convention: mri/reproin.md
          - Siemens Console Walkthrough: mri/walkthrough-1.md
        - EEG: XXX.md
        - MRS: XXX.md
    - Useful basics:
        - Shell: XXX.md
        - SSH: XXX.md
        - DataLad: XXX.md
        - Containers: XXX.md
        - PyBIDS: XXX.md
    - Data Access:
        - DICOMs: XXX.md
        - BIDS: XXX.md
    - Data Processing:
        - QA: XXX.md
        - Preprocessing: XXX.md
        - Analysis: XXX.md
        - Computing Resources:
            - Discovery HPC: XXX.md
    - Publishing:
        - Datasets: XXX.md
        - Papers:
            - Data descriptor: XXX.md
            - Study paper(s): XXX.md
    - Appendix:
        - Contributors: 99-appendices/01-contributors.md
        - Licenses: 99-appendices/02-licenses.md
    - Changelog: CHANGES.md
    - Contributing: CONTRIBUTING.md
    - DBIC Website: http://dartmouth.edu/dbic
    - DBIC GitHub: http://github.com/dbic
